sudo: false
language: python
python:
  - 2.7
  - 3.6
install: pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/speller"
  - export FLASK_DEBUG=1

script: flask routes
